id: A68802AF8
base_file: fEDD4.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:39:50.061229
  last_modified_at: 2022-05-30 20:39:50.061232
