id: A68802AF8
base_file: fC517.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:39:50.059708
  last_modified_at: 2022-05-30 20:39:50.059711
