id: A68802AF8
base_file: fB71B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:39:50.056943
  last_modified_at: 2022-05-30 20:39:50.056946
