id: A68802AF8
base_file: f2FF2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:39:50.053412
  last_modified_at: 2022-05-30 20:39:50.053420
